### ISSUE TITLE
 [FEATURE REQUEST] be able to turn on/off recording depending on gamemode

### ISSUE THREAD

**Issue by ceselder** [FFFFFFFXXXXXXX/league_record#18]
URF is live and I think I'm not the only one who is playing a lot of urf games haha. I mainly use this program for recording gameplay to review of my ranked games though, and its quite cumbersome to delete all urf replays manually.

It would be nice if we could simply turn on/off storage of recordings depending on the gamemode we're playing.

**Comment by FFFFFFFXXXXXXX** [comment]
I currently take most of the game information from the post game stats API.
This means I don't know until the game ends what type of gamemode is being played.

So this feature requires me to make some bigger changes to how I collect the data, but I'll keep it in mind.

**Comment by ceselder** [comment]
I think the implementation could be as simple as just getting info from postgame and then checking if the gamemode is a match that u want to record, and then deleting the recording if it isnt.

Its obviously not an ideal solution but I would rather have it over nothing and I'd imgine its very easy to implement. recording overhead is very minimal anyway

**Comment by FFFFFFFXXXXXXX** [comment]
Alright than I'll have to figure out #17 first.
Once I have that this should be doable. 

What do you want the settings to look like?
A new entry in the settings.json text file?

**Comment by ceselder** [comment]
Its your project! You decide! a new entry in settings.json is what I would go for aswell, and it would work nicely with my plugin. I think re-using checkboxes for objectives could be used, but it could also simply be like an array kinda notation in the settings text file

**Comment by FFFFFFFXXXXXXX** [comment]
Ok, I figured out how to properly get the queueId of the current game.
The thing is the queueId is one of these values: https://raw.communitydragon.org/latest/plugins/rcp-be-lol-game-data/global/default/v1/queues.json.
I don't think adding a seperate toggle for each of these is a good way to solve this.

How does your use-case look like / how would you group these?
My first thought was adding a setting that says "only record Ranked games".
Or do you want more finegrained control over what gets recorded?

**Comment by judehek** [comment]
i'd love "only record ranked", not much point in reviewing normals etc

**Comment by ceselder** [comment]
finegrained would be nice, but "only record ranked" does suffice.

**Comment by FFFFFFFXXXXXXX** [comment]
Alright, I just released pre-release [v1.18.0](https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.18.0).
It includes an option to only record ranked games in the settings.json and also addresses #17.

Because I had to make some big changes to get this working the new version doesn't read the old recording metadata files - so no events, stats, win/loss, ... for everything recorded with the old versions of the app.
@ceselder this means you will probably have to update your Obsidian plugin.

Please check it out and tell me if it works as expected :)

**Comment by FFFFFFFXXXXXXX** [comment]
I just released [v1.18.1](https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.18.1) which 'officially' implements Feature requests #17 and #18.
The new release also includes a fix for a bug from PRE-RELEASE 1.18.0 where sometimes games would not be recorded (again :sigh:)

**Comment by ceselder** [comment]
> I just released [v1.18.1](https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.18.1) which 'officially' implements Feature requests #17 and #18. The new release also includes a fix for a bug from PRE-RELEASE 1.18.0 where sometimes games would not be recorded (again :sigh:)

I'm still getting occasional moments where games are not recorded.

**Comment by FFFFFFFXXXXXXX** [comment]
if it happens again could you post the logs of it happening. Thanks!
(logs are in `C:/Users/<username>/AppData/Roaming/fx.LeagueRecord/logs`)
